### PR TITLE
lock rrule version to 2.6.4

### PR DESCRIPTION
**Pull request by pseudoralph**
Deprecated package rrule is broken and appears it may not receive a fix. Update node-ical's package.json to use the recommended version from rrule's author (https://www.npmjs.com/package/rrule)

### CODE REVIEW

**Comment by rejas** [comment]
since rrule seems to be maintained again (there is no deprecation notice anymore and a new version got released), might it be time to unlock it and update to the latest version @jens-maus ?

**Comment by jens-maus** [comment]
Good idea. However, careful studying of the changelog and changes might be required to not risk any regression here.

**Comment by rejas** [comment]
At first glance at the changelog doesnt indicate any logic changes https://github.com/jakubroztocil/rrule/blob/master/CHANGELOG.md

There is a breaking change mentioned: "Removes default export in favor of named exports" but you seem to already do that (the tests run fine with v2.7.1)

Should I prepare a PR or is that something you want to do?

**Comment by Apollon77** [comment]
The main question is tho if the isue why we pinned the old version was adressed! It was lastly not fixed in 2.6.9

The rwason for the pinning was https://github.com/jakubroztocil/rrule/issues/501#issuecomment-1146503580 and this is still open

**Pull request closed without merging**
