### PR TITLE
Refactor and Improve API

### PR DESCRIPTION
**Pull request by jackm-xyz**
Since I need to make some edits to the core of node-ical for a project of mine I made some improvements to both the code style, tooling, API and README.

In total this PR contains the following changes:
 - Used ESLint and Prettier to reformat code to be more readable and usable
 - Removed unneeded abstraction from `ical.js` to make it more native to Node
 - Merged some code from `index.js`, `ical.js` and `node-ical.js` into the correct `index.js` and `ical.js` files.
 - Rewrote API to allow for better performance (I'll come back to this) and ease of use while also being 100% backwards compatible

Hopefully this makes future changes much easier and allows for anyone new to this project to more easily understand the code.

Also for some reason the original API would accept callbacks but would not use ical.parseLines()'s callback feature. This caused some of the old API functions to block the event loop even if they were synchronous.

All API functions have been redesigned for performance but I made sure to keep compatibility with tools written using the old style. This PR is non-breaking and should work completely fine with any currently existing code.

New APIs have also been introduced to allow for better and more consistent code to be written. All of the old and new APIs have been both documented in README and documented inside of `index.js` with JSDoc. The JSDoc documentation allows for IDE hinting and auto-completion.
Screenshot from 2019-10-05 14-08-06
Screenshot from 2019-10-05 14-09-36

The README has also been updated to fix typos.

All tests pass and these changes work great with my already existing projects that use node-ical.
Screenshot from 2019-10-05 14-58-29

Thanks for reading and please consider merging these changes into node-ical.

If anyone would like to test the changes you can install the forked version by doing `npm install github:jackm-xyz/node-ical#refactor`.

### CODE REVIEW

**Comment by Archcry** [comment]
I took a quick look at the changes, if you're fixing the code style you might as well take a look at the various cases in which `var` is used. Replace those with either `const` or `let`.

**Comment by jens-maus** [comment]
I agree. I also had a quick look over your changes and I would love to integrate them. However, please fix at least const/let uses were appropriate.

**Comment by jackm-xyz** [comment]
I have updated the ESLint settings and changed any occurrences of `var` to `const` or `let` as appropriate.

**Comment by Archcry** [comment]
LGTM!

**Comment by jens-maus** [comment]
Thanks for the adaptions and thanks for the whole changes. Will integrate them right away and see if there is more to come (issues, other changes) and then release a new version shortly. Feel free to contribute more such enhancements!

**Pull request merged**
