### PR TITLE
FIX support webpack

### LINKED ISSUE #235: "Cannot find module '/var/task/src/handlers/windowsZones.json'" runtime error when node-ical in AWS Lambda function with webpack
I've encountered a runtime error when using node-ical in an AWS Lambda function that is deployed using Serverless with the serverless-webpack plugin.

tl;dr;

Change line 107 of ical.js function `getIanaTZFromMS` from

```
zoneTable = require(p.join(__dirname, 'windowsZones.json'));
```

to

```
zoneTable = require('./windowsZones.json')
```

## Detailed(ish) analysis

This is the warning message from the serverless-webpack plugin on `serverless package` or `serverless deploy`:

```
Running "serverless" from node_modulesPackaging eee-calendar-service for stage dev (us-east-1)Warning: in 
  in ./node_modules/node-ical/ical.js 107:16-63
  Critical dependency: the request of a dependency is an expression 
```

This is the error that occurs at runtime

```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '/var/task/src/handlers/windowsZones.json'",
    "code": "MODULE_NOT_FOUND",
    "stack": [
        "Error: Cannot find module '/var/task/src/handlers/windowsZones.json'",
        "    at t (/var/task/src/handlers/index.js:2:503736)",
        "    at f (/var/task/src/handlers/index.js:2:365763)",
        "    at /var/task/src/handlers/index.js:2:366739",
        "    at Object.DTSTART (/var/task/src/handlers/index.js:2:370102)",
        "    at Object.handleObject (/var/task/src/handlers/index.js:2:371365)",
        "    at Object.parseLines (/var/task/src/handlers/index.js:2:371916)",
        "    at Object.parseICS (/var/task/src/handlers/index.js:2:372210)",
        "    at /var/task/src/handlers/index.js:2:372723",
        "    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)"
    ]
} 
```

Local Version information
node: 16.18.1
node-ical: 0.15.1
serverless:
       Framework Core: 3.21.0 (local) 3.22.0 (global)
       Plugin: 6.2.2
       SDK: 4.3.2 
serverless-webpack: 5.7.1

### PR DESCRIPTION
**Pull request by madzim**
fixes: https://github.com/jens-maus/node-ical/issues/235

> Cannot find module '/var/task/src/handlers/windowsZones.json'" runtime error when node-ical in AWS Lambda function with webpack

### CODE REVIEW

**Comment by sdetweil** [comment]
could u edit your post and change the reference like below',, then github will link the PR to the issue in the issue page

fixes: #235

**Comment by madzim** [comment]
@sdetweil done. sorry 'bout that. I've done very few contributions to repos.

**Comment by sdetweil** [comment]
@madzim thanks. I didn't know either  til a few months ago. 5 yrs  and still learning!!!

**Comment by madzim** [comment]
Ugg, I made a little mess with an errant commit that has been reverted.
Let me know if I need to recreate a PR.

**Comment by jens-maus** [comment]
Instead of using `./windowsZones.json` I would suggest to use a `path.resolve()` solution similar to this change:

https://github.com/axios/axios/pull/5269/files#diff-cfd111adb0388d60ebe5d359e21d027ed30f9c407412bc06f5fb5a0ab55fd657R14

To me this looks like a better approach in trying to get rid of the `__dirname` issue.

**Comment by sdetweil** [comment]
@madzim 
this does not work for MagicMirror use of this module.. 
https://github.com/MichMich/MagicMirror

we execute in ~/MagicMirror
but the file is in ~/MagicMirror/node_modules/node-ical

so '.' causes this to fail 
```
zoneTable = require(p.join('.', 'windowsZones.json'));
```
@jens-maus 
path.resolve() also fails, as the node_modules/node-ical is not in the path
```
zoneTable = require(p.join(p.resolve(), 'windowsZones.json'));
```

**Comment by madzim** [comment]
Thanks for the responses.

I've spent most of the last two days trying to understand @jens-maus suggestion and @sdetweil MagicMirror comment.

This is a long response because I want to demonstrate that testing I performed and the problems I had that have led me to the conclusion that this PR works.

tl;dr;

1. The PR works; more about my problems testing with MagicMirror below.
2. @jens-maus suggestion also fails webpack validation because webpack requires `require(LITERAL)`.
3. MagicMirror has problems that I don't understand.

**1. The PR works**

The Module loader is correctly setting __dirname and __filename within the node-ical project.
My test is dirty, but I just inserted these two lines at the tope of node_modules/node-ical/ical.js

`
console.log('node-ical __dirname:', __dirname);
console.log('node-ical __filename:', __filename);
`

From terminal, ran this:

`
% node -e "require('node-ical')"
`

which output:

`
node-ical __dirname: /Users/cpatrick/code/github/MagicMirror/node_modules/node-ical
node-ical __filename: /Users/cpatrick/code/github/MagicMirror/node_modules/node-ical/ical.js
`

**2. @jens-maus suggestion also fails webpack**

Webpack seems to want string literals.

I tried to be sneaky and do something like `require( "" + path.join(....) )` but webpack saw right through the ruse.

**3. MagicMirror has problems**

I wanted to see what @sdetweil was seeing so I tried to using install directly to my project.

spoiler alert: the default ICS file with MagicMirror doesn't seem to invoke the ical.getIanaTZFromMS() function.

Before I got there, I tried to use my PR code in MagicMirror using `npm link` (fail) and `npm ./path/to/my/fork/node-ical`.

I used this command to remove the existing 0.15.3 node-ical and install my local one.

`npm uninstall node-ical && npm install ../madzim/node-ical`

Package.json looks correct

`
		"node-fetch": "^2.6.7",
		"node-ical": "file:../madzim/node-ical",
		"socket.io": "^4.5.4"
`

Then start MM

`
npm run start:dev
`

and get this error

`
[05.01.2023 17:18.10.736] [ERROR] Calendar Error. Could not fetch calendar:  http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics TypeError: Cannot read properties of undefined (reading 'guess')
    at Object.calculateTimezoneAdjustment (/Users/cpatrick/code/github/MagicMirror/modules/default/calendar/calendarutils.js:30:31)
    at /Users/cpatrick/code/github/MagicMirror/modules/default/calendar/calendarutils.js:489:37
    at Array.forEach (<anonymous>)
    at Object.filterEvents (/Users/cpatrick/code/github/MagicMirror/modules/default/calendar/calendarutils.js:142:24)
    at /Users/cpatrick/code/github/MagicMirror/modules/default/calendar/calendarfetcher.js:74:29
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
`

I debugged and tracked the error to ical.js #122 

`
tz = moment.tz.guess();
`

For some reason, `moment.tz` is `null`.

I realized that my fork was several commits behind master, merged to my branch, and tried again.

Same error.

Then a just switched to `master`... I did not reapply my changes.

Same error.

The I noticed that master is several commits beyond the 0.15.3 branch so I switched to d88b01f .

Same error.

So I have no clue what is happening there and I abandoned my local branch all together.

**I'm baffled**

I don't know why MagicMirror hates using symlink.

It could be some moment version conflict...dunno.

**Comment by sdetweil** [comment]
I'm the one that created the windowszones looking table file.

the pr does NOT work, as it removes __dirname and uses ./

the current directory when MagicMirror is executing is ~/MagicMirror

and ./  does not find the zone file there.

the path.resolve() suggestion is to let path module build the  full path, given it's potential parts.. if one can figure out what those should be.

MagicMirror doesn't use webpack, as this componentry runs on the server side under nodejs. 

I don't know why you are having trouble with moment.  

when I am testing possibilities, I edit the code in the node modules folder directly, and don't involve npm.

one can edit the ical.js to force calling the getiana function. saves a lot of debug time

**Comment by madzim** [comment]
> when I am testing possibilities, I edit the code in the node modules folder directly, and don't involve npm.

I did the same; I omitted the details to keep that response from getting too verbose.

So what are we doing differently?

Below I'll walk through what I've done.

### Context

1. I'm on OSX
2. Using current master of MagicMirror (2eaf9dfe)
3. I'm using the default MM config.js.
4. I've modified `ical.js/parseICS()` to force a call to `getIanaTZFromMS()` because the default US_Holidays.ics file does not contain Windows Timezones.
5. I've tested using latest NodeJS: 16.18.1 and 18.12.0
6. I'm using nvm to switch version
7. After switching node version, I `rm -rf node_modules`, `npm ci`, and then `cp ical.js node_modules/node-ical/ical.js`

In the console output, we can see that `zoneTable` was successfully loaded:

> ...
> [10.01.2023 11:32.04.589] [LOG]   zzzzzzzz parseICS
> [10.01.2023 11:32.04.591] [LOG]   zzzzz: calling getIanaTZFromMS()
> [10.01.2023 11:32.04.591] [LOG]   xxxxxx loading windowsZone. __dirname:  /Users/cpatrick/code/github/MagicMirror/node_modules/node-ical
> [10.01.2023 11:32.04.594] [LOG]   zoneTable:  {
>   'Dateline Standard Time': { iana: [ 'Etc/GMT+12' ] },
>   'UTC-11': { iana: [ 'Etc/GMT+11' ] },
> ...

### modified ical.json is attached

[ical.zip](https://github.com/jens-maus/node-ical/files/10385366/ical.zip)

### Diff of the files

[ical.js.diff.zip](https://github.com/jens-maus/node-ical/files/10385409/ical.js.diff.zip)

### Expanded diff

106,110c106,107
<     // const p = require('path');
<     // zoneTable = require(p.join(__dirname, 'windowsZones.json'));
<     console.log('xxxxxx loading windowsZone. __dirname: ', __dirname);
<     zoneTable = require('./windowsZones.json');
<     console.log('zoneTable: ', zoneTable);
---
>     const p = require('path');
>     zoneTable = require(p.join(__dirname, 'windowsZones.json'));
717d713
<     console.log('zzzzzzzz parseICS');
727,729d722
<       console.log('zzzzz: calling getIanaTZFromMS()');
<       const foo = getIanaTZFromMS('Central Standard Time');
<       console.log('zzzzzz foo:', foo);

**Comment by sdetweil** [comment]
doh, I missed the commented out lines.. 


well, I don't know whats different put your PR works...  tried on 2 different systems...  I withdraw my complaint

**Comment by madzim** [comment]
@sdetweil 
haha No worries. I was really concerned too that we were seeing different behaviors. :cringe: 

Is there anything else I need to do help get this into a release?

We're also waiting for the the luxon patch to address a vulnerability Snyk is reporting: https://github.com/jens-maus/node-ical/pull/243

**Comment by zackdotcomputer** [comment]
Would very much also like this to be merged and deployed. I'm using `node-ical` directly in a NextJS application, where the server-side is compiled with Webpack for serverless deploy, and am thus running into this issue where webpack wants `require` to only ever be called with a static string.

**Pull request merged**
