### PR TITLE
calendar metadata

### PR DESCRIPTION
**Pull request by Flowr-es**
I discovered that the calendar metadata (Timezone, Calendarname, etc.) get deleted by intention

As there are at least from my understanding important information get deleted I decided to extend this lib and add all VCalendar metadata into an record.

Also I replaced uuid with nanoid that is a better lib and also used by the most popular ical creator libs.

Sorry for the package.json space or line break changes. Hope that is no problem for you.

As this is a kind of breaking change I fully understand that this needs a proper revision.

### CODE REVIEW

**Comment by Apollon77** [comment]
Whats the benefit of nanoid vs uuid? uuid is also used "evrywhere" where a uuid is needed :-)

**Comment by Flowr-es** [comment]
nanoid is smaller and faster compared to uuid

However uuid isn't bad, so I can revert this part if uuid is preferred

**Comment by Apollon77** [comment]
I think @jens-maus needs to say that  in the end .. I was just interested because I did not even knwo the other lib :-) aahhh end it does not generate UUIDs at all ... that would then be kind if a breaking change pot. No idea if someone expects it to be a UUID

**Comment by Flowr-es** [comment]
that is true,. the format of a nanoid is not in the uuid format. I will revert this part, I fully agree that it should be a uuid.
This lib is used by ical-generator and looks also better as the standard uuid lib: https://www.npmjs.com/package/uuid-random 

However I guess the performance is actually not that important, it would only be a benefit if someone is using the generator and the parser lib ;-)

**Pull request merged**
