### PR TITLE
New windows timezone support, updated approach

### PR DESCRIPTION
**Pull request by sdetweil**
checkout this approach  if approved I will close these PRs and create a new clean one this way

this creates the hash table as a postinstall step, converted to json to load/parse on demand. all conversion logic moved to postinstall

### CODE REVIEW

**Comment by jens-maus** [comment]
Sorry, but there is no need to always create a new pull request for every change you want to see integrated. Please simply continue adding changes to one PR as I will squash it together into one changeset when I am going to merge it anyway.

In addition, to be able to review your PR/changes please get away from these dozens of white space changes or unnecessary style changes in ical.js which your PR suggests. Changes like these should not be submitted with a PR that is supposed to introduce/change functionality. If you want to suggest code style changes, please open a separate PR for it. So please rework this PR to not introduce code style changes or unnecessary white space/tabulator changes so that I can better review what you are actually suggesting to be integrated. And please obey to the currently used code style even if this might not be your taste.

**Comment by sdetweil** [comment]
I didn't make any whitespace changes. I ran npm run format fix 

to correct a source formatting error bef, during the commit. the commit ran the git precommit hook.

I don't know what the problem is here. I am using the same folder as before, on linux. I only edited the two .js files ical.js an cvt-to-json.js and postinstall

**Comment by jens-maus** [comment]
@sdetweil you are right, I forgot to run `npm run format` myself for a long time ;) I just did now. So please rebase your PR onto the latest master changes so that the conflicts are going away and I can do a clean review. Thanks.

**Comment by jens-maus** [comment]
Wait a minute. I am currently investigating this white-space mess here.

**Comment by jens-maus** [comment]
Ok, now I am done with cleaning all the style stuff up. So please update your fork to the latest master of node-ical and update this PR so that only the relevant changes should be visible. And in future, please use `npm run lint` and/or `npm run lintfix` if you want to check for code style changes, etc. the `format` option had been retired, btw.

**Comment by sdetweil** [comment]
ok, can't figure out how to get new stuff merged.. closing, new fork, then new pr..

**Comment by jens-maus** [comment]
Ok, as you wish. But as said before, usually you can simply commit to the branch you are using for the pull-request. So you simply have to fetch the latest sources from upstream again (using `git fetch upstream`) and then merge in the upstream/master. denn cleanup everything and commit to the branch you used for the PR. Completly deleting your fork and starting from scratch is usually not the best approach/way.

**Pull request closed without merging**
